POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJ2aWxsZSIsImlkIjoiNjNlYTI4MDlmNTQzMzM4MjhlNjRmNGQzIiwiaWF0IjoxNjc2ODAxODUyfQ.d7JBCyfakz8FAx8xXjCoKMIklEwsl9mxhluopJmmTZk

{
    "title": "Päiväni lintumetällä",
    "url": "www.lintumetalla.net"
}